export const dayList = [
  null,
  null,
  null,
  null,
  {
    EmotionStatus: 1,
    date: '2023. 12. 05.',
    id: 1,
    image: '/pig.png',
    content: '피곤하다',
    sentence: '개천에서 용 난다.',
    writer: '주철민',
  },
  {
    EmotionStatus: 2,
    date: '2023. 12. 06.',
    id: 2,
    image: '/rabbit.png',
    content: '배고프다',
    sentence: '돌다리도 두들겨 보고 건너라',
    writer: '한덕용',
  },
  null,
  null,
  null,
  {
    EmotionStatus: 3,
    date: '2023. 12. 10.',
    id: 3,
    image: '/me.png',
    content: '화이팅이다.',
    sentence: '모르는 게 약이다',
    writer: '송지우',
  },
  null,
  null,
  {
    EmotionStatus: 4,
    date: '2023. 12. 13.',
    id: 4,
    image: '/happy.png',
    content: '그림일기 재밌다',
    sentence: '아는 게 힘이다 !',
    writer: '이승연',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  {
    EmotionStatus: 3,
    date: '2023. 12. 21.',
    id: 5,
    image: '/angry.png',
    content: '라면은 안성탕면',
    sentence: '행복하자 ~~',
    writer: '유재현',
  },
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  null,
  {
    EmotionStatus: 3,
    date: '2023. 12. 30.',
    id: 6,
    image: '/sad.png',
    content: '노래 추천 받아요',
    sentence: '할 수 있다 !',
    writer: '이찬영',
  },
];
